In [1]:
import numpy as np
import pandas as pd

In [2]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)

In [3]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [4]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [6]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [7]:
values2 = pd.Series([0,1,0,0] * 2)

In [8]:
dim = pd.Series(['apple', 'orange'])

In [9]:
values2

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [10]:
dim

0     apple
1    orange
dtype: object

In [11]:
dim.take(values2)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [1]:
fruits=['apple','orange','apple','apple'] * 2

In [2]:
N=len(fruits)

In [8]:
df=pd.DataFrame({'fruit': fruits,
                'basket_id': np.arange(N),
                'count': np.random.randint(3, 15, size=N),
                'weight': np.random.uniform(0,4,size=N)},
               columns=['basket_id','fruit','count','weight'])

In [9]:
df

basket_id   fruit  count    weight
0          0   apple      3  1.354150
1          1  orange      3  2.342192
2          2   apple      3  1.131885
3          3   apple      3  0.845259
4          4   apple      3  0.616349
5          5  orange     12  3.969491
6          6   apple      5  3.845400
7          7   apple      6  0.638807

In [10]:
fruit_cat = df['fruit'].astype('category')

In [11]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [12]:
c=fruit_cat.values
type(c)

pandas.core.arrays.categorical.Categorical

In [13]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [14]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [15]:
df['fruit'] = df['fruit'].astype('category')

In [16]:
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [18]:
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])

In [19]:
my_categories

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [20]:
categories = ['foo','bar','baz']

In [21]:
codes=[0,1,2,0,0,1]

In [22]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [23]:
my_cats_2

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo, bar, baz]

In [24]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [25]:
ordered_cat

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [26]:
my_cats_2.as_ordered()

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [27]:
np.random.seed(12345)

In [28]:
draws = np.random.randn(1000)

In [29]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [30]:
bins=pd.qcut(draws, 4)

In [31]:
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [32]:
bins2 = pd.qcut(draws, 4, labels=['Q1','Q2','Q3','Q4'])

In [33]:
bins2

[Q2, Q3, Q2, Q2, Q4, ..., Q3, Q2, Q1, Q3, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [35]:
bins2.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [36]:
bins2 = pd.Series(bins2, name='quartile')

In [38]:
results = (pd.Series(draws)
          .groupby(bins2)
          .agg(['count', 'min', 'max'])
          .reset_index())

In [39]:
results

quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

In [40]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [41]:
N3 = 10000000

In [42]:
draws3 = pd.Series(np.random.randn(N3))

In [43]:
labels3 = pd.Series(['foo','bar','baz','qux'] * (N3//4))

In [44]:
categories3 = labels3.astype('category')

In [45]:
labels3.memory_usage()

80000128

In [46]:
categories3.memory_usage()

10000320

In [48]:
%timeit _ = labels3.astype('category')

940 ms ± 75.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
