In [1]:
import numpy as np

In [2]:
arr=np.arange(12).reshape((3,4))

In [3]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [5]:
np.concatenate([arr, arr], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
import pandas as pd

In [7]:
s1=pd.Series([0,1], index=['a','b'])

In [8]:
s2=pd.Series([2,3,4],index=['c','d','e'])

In [9]:
s3=pd.Series([5,6],index=['f','g'])

In [10]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [37]:
pd.concat([s1,s2,s3], axis=1, sort=False)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [12]:
s4=pd.concat([s1,s3])

In [13]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [34]:
pd.concat([s1,s4], axis=1, sort=False)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [15]:
pd.concat([s1,s4], axis=1, join='inner')

0  1
a  0  0
b  1  1

In [36]:
pd.concat([s1,s4], axis=1, join_axes=[['a','c','b','e']])

C:\Users\stepheny.sisi.yuan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  """Entry point for launching an IPython kernel.


0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

In [20]:
result=pd.concat([s1,s1,s3], keys=['one','two','three'])

In [21]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [22]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [23]:
result.unstack().stack()

one    a    0.0
       b    1.0
two    a    0.0
       b    1.0
three  f    5.0
       g    6.0
dtype: float64

In [33]:
pd.concat([s1,s2,s3], axis=1, keys=['one','two','three'], sort=False)

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [25]:
df1=pd.DataFrame(np.arange(6).reshape(3,2), index=['a','b','c'],
                columns=['one','two'])

In [26]:
df2=pd.DataFrame(5+np.arange(4).reshape(2,2), index=['a','c'],
                columns=['three','four'])

In [27]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [28]:
df2

three  four
a      5     6
c      7     8

In [32]:
pd.concat([df1, df2], axis=1, keys=['level1','level2'], sort=False)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [31]:
pd.concat({'level1':df1, 'level2':df2}, axis=1, sort=False)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [38]:
pd.concat([df1, df2], axis=1, keys=['level1','level2'], 
          names=['Axis0_1', 'Axis0_2'], sort=False)

Axis0_1 level1     level2     
Axis0_2    one two  three four
a            0   1    5.0  6.0
b            2   3    NaN  NaN
c            4   5    7.0  8.0

In [39]:
df3=pd.DataFrame(np.random.randn(3,4), columns=['a','b','c','d'])

In [42]:
df4=pd.DataFrame(np.random.randn(2,3), columns=['b','d','a'])

In [44]:
df3

a         b         c         d
0  0.381538  0.733153 -0.757195 -0.440985
1 -0.684187 -0.482197  0.742085 -1.018766
2  0.225665  0.157926 -0.234091  1.792789

In [45]:
df4

b         d         a
0 -2.129200  1.045161  0.273719
1  1.039956 -0.393684  1.318019

In [47]:
pd.concat([df3, df4], ignore_index=True, sort=False)

a         b         c         d
0  0.381538  0.733153 -0.757195 -0.440985
1 -0.684187 -0.482197  0.742085 -1.018766
2  0.225665  0.157926 -0.234091  1.792789
3  0.273719 -2.129200       NaN  1.045161
4  1.318019  1.039956       NaN -0.393684