In [6]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [7]:
def dnorm(mean, variance, sizeInput=1):
    if isinstance(sizeInput, int):
        size = sizeInput,
    return mean + np.sqrt(variance) * np.random.randn(*size)

In [8]:
np.random.seed(12345)

In [9]:
N=100

In [10]:
X = np.c_[dnorm(0, 0.4, sizeInput=N),
         dnorm(0, 0.6, sizeInput=N),
         dnorm(0, 0.2, sizeInput=N)]

In [11]:
eps = dnorm(0, 0.1, sizeInput=N)

In [12]:
beta = [0.1, 0.3, 0.5]

In [13]:
y=np.dot(X, beta) + eps

In [14]:
X[:10]

array([[-0.12946849, -1.21275292,  0.50422488],
       [ 0.30291036, -0.43574176, -0.25417986],
       [-0.32852189, -0.02530153,  0.13835097],
       [-0.35147471, -0.71960511, -0.25821463],
       [ 1.2432688 , -0.37379916, -0.52262905],
       [ 0.88126723, -0.02808985, -0.36896015],
       [ 0.0587601 ,  0.84848549, -1.18261588],
       [ 0.17819191,  0.75982393, -0.06841733],
       [ 0.48637258, -0.4566152 , -0.3362693 ],
       [ 0.78831454,  1.22517962, -0.05930466]])

In [15]:
y[:10]

array([ 0.42786349, -0.67348041, -0.09087764, -0.48949442, -0.12894109,
       -0.04501494,  0.08757735, -0.50456809, -0.54582359,  0.26527124])

In [16]:
X_model = sm.add_constant(X)

In [17]:
X_model[:10]

array([[ 1.        , -0.12946849, -1.21275292,  0.50422488],
       [ 1.        ,  0.30291036, -0.43574176, -0.25417986],
       [ 1.        , -0.32852189, -0.02530153,  0.13835097],
       [ 1.        , -0.35147471, -0.71960511, -0.25821463],
       [ 1.        ,  1.2432688 , -0.37379916, -0.52262905],
       [ 1.        ,  0.88126723, -0.02808985, -0.36896015],
       [ 1.        ,  0.0587601 ,  0.84848549, -1.18261588],
       [ 1.        ,  0.17819191,  0.75982393, -0.06841733],
       [ 1.        ,  0.48637258, -0.4566152 , -0.3362693 ],
       [ 1.        ,  0.78831454,  1.22517962, -0.05930466]])

In [18]:
model = sm.OLS(y, X)

In [19]:
results = model.fit()

In [20]:
results.params

array([0.17826108, 0.22303962, 0.50095093])

In [21]:
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.430
Model:                            OLS   Adj. R-squared (uncentered):              0.413
Method:                 Least Squares   F-statistic:                              24.42
Date:                Tue, 14 Jan 2020   Prob (F-statistic):                    7.44e-12
Time:                        10:16:10   Log-Likelihood:                         -34.305
No. Observations:                 100   AIC:                                      74.61
Df Residuals:                      97   BIC:                                      82.42
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [29]:
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])

In [30]:
data['y']=y


In [31]:
data[:10]

col0      col1      col2         y
0 -0.129468 -1.212753  0.504225  0.427863
1  0.302910 -0.435742 -0.254180 -0.673480
2 -0.328522 -0.025302  0.138351 -0.090878
3 -0.351475 -0.719605 -0.258215 -0.489494
4  1.243269 -0.373799 -0.522629 -0.128941
5  0.881267 -0.028090 -0.368960 -0.045015
6  0.058760  0.848485 -1.182616  0.087577
7  0.178192  0.759824 -0.068417 -0.504568
8  0.486373 -0.456615 -0.336269 -0.545824
9  0.788315  1.225180 -0.059305  0.265271

In [34]:
results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()

In [35]:
results.params

Intercept    0.033559
col0         0.176149
col1         0.224826
col2         0.514808
dtype: float64

In [36]:
results.tvalues

Intercept    0.952188
col0         3.319754
col1         4.850730
col2         6.303971
dtype: float64

In [37]:
results.predict(data[:10])

0   -0.002327
1   -0.141904
2    0.041226
3   -0.323070
4   -0.100535
5   -0.007466
6   -0.374149
7    0.200553
8   -0.156541
9    0.417341
dtype: float64