In [14]:
import random
import statsmodels.api as sm

In [1]:
init_x = 4

In [2]:
values = [init_x, init_x]

In [3]:
N=1000

In [4]:
b0 = 0.8

In [5]:
b1 = -0.4

In [9]:
def dnorm(mean, variance, sizeInput=1):
    if isinstance(sizeInput, int):
        size = sizeInput,
    return mean + np.sqrt(variance) * np.random.randn(*size)

In [10]:
noise = dnorm(0, 0.1, N)

In [11]:
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)

In [22]:
values

[4,
 4,
 1.8072329548488202,
 -0.29765126055386537,
 -0.45661614525275995,
 -0.2117064098783575,
 0.11108539365221391,
 -0.39033408326372643,
 -0.6880635990009301,
 -0.6327433076171267,
 -0.18102030996213161,
 -0.01954882035686195,
 -0.22416311506447262,
 0.1586942448736908,
 0.4622699911425687,
 0.48208093014081077,
 0.15962722646684835,
 0.30892525450882025,
 -0.07043899809373189,
 -0.5948102613737922,
 -1.1006223463186902,
 -0.6829402847212646,
 0.0658166282745134,
 0.025380238670660804,
 -0.13349616733446015,
 0.01124658944817547,
 0.12858681240166983,
 -0.036492906764457475,
 0.3364384921545859,
 0.8097657809218224,
 0.3577341234008265,
 -0.0495147211753105,
 -0.08783659831621751,
 -0.06472840496505008,
 0.24626655264964287,
 0.6572884326187777,
 0.947224613496624,
 0.4722132667529168,
 0.2680462887453787,
 0.0801445160354246,
 -0.11879976023037078,
 -0.5718290391601132,
 -0.34927952418368935,
 0.14793011478512338,
 0.19360764042397133,
 0.3397241620529238,
 -0.13741838011677143,


In [23]:
len(values)

1002

In [12]:
MAXLAGS = 5

In [15]:
model = sm.tsa.AR(values)

In [16]:
results = model.fit(MAXLAGS)

In [17]:
results.params

array([ 0.00086299,  0.76285013, -0.36993723, -0.05700544,  0.05696726,
        0.01279941])

In [20]:
results.tvalues

array([ 0.08953022, 24.0337003 , -9.26958303, -1.37030563,  1.44021504,
        0.42671738])

In [21]:
results.predict()

array([-6.13098581e-02,  1.79400531e-01,  1.96127327e-01, -3.55751557e-01,
       -4.03864536e-01, -2.01415308e-01,  1.15255862e-01,  4.47929877e-02,
       -1.97441357e-01,  1.87552609e-01,  3.04146721e-01,  1.75540999e-01,
       -7.58857346e-02,  1.78358811e-01, -1.42874376e-01, -4.29176636e-01,
       -5.95047290e-01, -7.91081495e-02,  3.31671425e-01, -3.55050610e-02,
       -1.67108138e-01,  5.23889964e-02,  1.04693185e-01, -8.24658577e-02,
        2.62617085e-01,  5.03681276e-01, -4.54138927e-02, -1.96710664e-01,
       -1.77822789e-02,  1.75452076e-02,  2.19438138e-01,  4.09224688e-01,
        4.61447753e-01, -1.35910868e-02,  1.72518906e-02, -1.70409541e-03,
       -9.56673522e-02, -3.74663178e-01, -3.92754129e-02,  2.69778467e-01,
        7.96464779e-02,  1.52749539e-01, -2.36723349e-01,  1.38095587e-02,
        7.39555998e-02,  1.97500990e-01,  6.17637022e-01,  7.10571261e-01,
       -4.82904917e-02, -4.53849381e-01, -1.98506268e-01, -1.44107503e-01,
        2.40445210e-01,  