In [2]:
import numpy as np

In [3]:
xarr=np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [4]:
yarr=np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [7]:
cond = np.array([True, False, True, True, False])

In [13]:
import time as tm

In [14]:
tm.time()
result=[(x if c else y)for x,y,c in zip(xarr, yarr, cond)]
tm.time()

1576813992.9513073

In [17]:
tm.time()
result2 = np.where(cond, xarr, yarr)
tm.time()

1576822753.0263457

In [18]:
arr=np.random.randn(4,4)

In [19]:
arr

array([[-0.21345205,  1.44147786,  1.1806331 ,  2.33667391],
       [ 1.17678965,  0.00359962,  0.52641752, -1.76242449],
       [ 2.1902787 ,  2.85085147,  0.15985759,  0.90973062],
       [ 1.48990056, -1.33549118,  1.45393428,  0.32727448]])

In [20]:
np.where(arr>0,2,arr)

array([[-0.21345205,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        , -1.76242449],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        , -1.33549118,  2.        ,  2.        ]])

In [21]:
arr2 = np.random.randn(5,4)

In [22]:
arr2

array([[ 0.84918313,  1.09317249, -0.64804599, -0.51651821],
       [ 0.5940842 ,  0.75625739,  1.32525933,  1.11397826],
       [-0.03752079, -0.68069114, -0.45559245,  0.36976428],
       [ 0.59693311, -0.87922685, -1.69842587,  1.28334475],
       [-1.71841809, -2.34407754,  0.95426248, -1.34809029]])

In [23]:
arr2.mean()

-0.06951839089187359

In [25]:
arr2.sum()

-1.3903678178374719

In [26]:
arr2.mean(axis=1)

array([ 0.19444785,  0.94739479, -0.20101003, -0.17434372, -1.11408086])

In [27]:
arr2.sum(axis=0)

array([ 0.28426157, -2.05456566, -0.52254251,  0.90247879])

In [28]:
arr3=np.array([0,1,2,3,4,5,6,7])

In [29]:
arr3.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [30]:
arr3.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [34]:
arr4=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [35]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
arr4.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [37]:
arr4.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [38]:
bools = np.array([0,0,1,0,0])

In [39]:
bools.any()

True

In [40]:
bools.all()

False

In [41]:
arr2.sort()

In [42]:
arr2

array([[-0.64804599, -0.51651821,  0.84918313,  1.09317249],
       [ 0.5940842 ,  0.75625739,  1.11397826,  1.32525933],
       [-0.68069114, -0.45559245, -0.03752079,  0.36976428],
       [-1.69842587, -0.87922685,  0.59693311,  1.28334475],
       [-2.34407754, -1.71841809, -1.34809029,  0.95426248]])

In [43]:
arr2.sort(1)

In [44]:
arr2

array([[-0.64804599, -0.51651821,  0.84918313,  1.09317249],
       [ 0.5940842 ,  0.75625739,  1.11397826,  1.32525933],
       [-0.68069114, -0.45559245, -0.03752079,  0.36976428],
       [-1.69842587, -0.87922685,  0.59693311,  1.28334475],
       [-2.34407754, -1.71841809, -1.34809029,  0.95426248]])

In [45]:
arr2.sort(0)

In [46]:
arr2

array([[-2.34407754, -1.71841809, -1.34809029,  0.36976428],
       [-1.69842587, -0.87922685, -0.03752079,  0.95426248],
       [-0.68069114, -0.51651821,  0.59693311,  1.09317249],
       [-0.64804599, -0.45559245,  0.84918313,  1.28334475],
       [ 0.5940842 ,  0.75625739,  1.11397826,  1.32525933]])

In [47]:
arr2=np.random.randn(5,4)

In [48]:
arr2

array([[-1.28625509, -1.50939174,  0.71771558, -0.67152312],
       [ 1.68268855,  0.50915777, -2.24672757,  0.56627171],
       [ 1.01231077,  2.15416613, -0.67897605,  0.70467498],
       [ 0.66787704,  0.54783949, -1.2873727 , -0.48776889],
       [ 0.45646441, -0.18271468, -0.11763709,  0.34377034]])

In [49]:
arr2.sort(0)

In [50]:
arr2

array([[-1.28625509, -1.50939174, -2.24672757, -0.67152312],
       [ 0.45646441, -0.18271468, -1.2873727 , -0.48776889],
       [ 0.66787704,  0.50915777, -0.67897605,  0.34377034],
       [ 1.01231077,  0.54783949, -0.11763709,  0.56627171],
       [ 1.68268855,  2.15416613,  0.71771558,  0.70467498]])

In [72]:
arrCopy1=np.random.randn(5,4)

In [73]:
arrCopy2=arrCopy1.copy()

In [74]:
arrCopy2

array([[ 0.20504243, -0.47264583,  0.25233016,  1.47373377],
       [-0.79237533,  2.06936327, -0.02523517,  0.66177771],
       [ 2.06859388,  0.50753679, -0.46567574,  0.10675202],
       [ 0.13491132, -1.03859913,  0.9129199 , -0.53188177],
       [ 0.55983156,  1.79950979,  1.90191184,  0.99654333]])

In [75]:
arrCopy1

array([[ 0.20504243, -0.47264583,  0.25233016,  1.47373377],
       [-0.79237533,  2.06936327, -0.02523517,  0.66177771],
       [ 2.06859388,  0.50753679, -0.46567574,  0.10675202],
       [ 0.13491132, -1.03859913,  0.9129199 , -0.53188177],
       [ 0.55983156,  1.79950979,  1.90191184,  0.99654333]])

In [76]:
arrCopy1.sort(0)

In [77]:
arrCopy1.sort(1)

In [78]:
arrCopy1

array([[-1.03859913, -0.79237533, -0.53188177, -0.46567574],
       [-0.47264583, -0.02523517,  0.10675202,  0.13491132],
       [ 0.20504243,  0.25233016,  0.50753679,  0.66177771],
       [ 0.55983156,  0.9129199 ,  0.99654333,  1.79950979],
       [ 1.47373377,  1.90191184,  2.06859388,  2.06936327]])

In [79]:
arrCopy2

array([[ 0.20504243, -0.47264583,  0.25233016,  1.47373377],
       [-0.79237533,  2.06936327, -0.02523517,  0.66177771],
       [ 2.06859388,  0.50753679, -0.46567574,  0.10675202],
       [ 0.13491132, -1.03859913,  0.9129199 , -0.53188177],
       [ 0.55983156,  1.79950979,  1.90191184,  0.99654333]])

In [80]:
arrCopy2.sort(1)

In [81]:
arrCopy2.sort(0)

In [82]:
arrCopy2

array([[-1.03859913, -0.53188177,  0.13491132,  0.9129199 ],
       [-0.79237533, -0.02523517,  0.25233016,  1.47373377],
       [-0.47264583,  0.10675202,  0.50753679,  1.90191184],
       [-0.46567574,  0.20504243,  0.66177771,  2.06859388],
       [ 0.55983156,  0.99654333,  1.79950979,  2.06936327]])