In [1]:
import numpy as np

In [2]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [3]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [4]:
ints1=np.array([1,3,5,7,9,2,4,6])

In [7]:
ints2=np.array([2,4,6,8,0])

In [9]:
np.intersect1d(ints1,ints2)

array([2, 4, 6])

In [10]:
np.unique(ints1)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [11]:
np.union1d(ints1,ints2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.in1