In [1]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [7]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [10]:
arr2d[:2,1:,-1]

IndexError: too many indices for array

In [11]:
arr2d[:2,-1]

array([3, 6])

In [12]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2d[:2,2]

array([3, 6])

In [15]:
arr2d[1,:2]

array([4, 5])

In [16]:
arr2d[-2,:2]

array([4, 5])