In [2]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
x=np.random.randn(8)

In [6]:
y=np.random.randn(8)

In [7]:
x

array([-0.31392823, -0.20190307, -0.84760833,  0.89853631,  0.14830707,
        0.28291022, -0.26877909,  0.72912856])

In [8]:
y

array([ 0.89424365, -1.26779302,  0.48444   , -1.11390411, -0.63554995,
       -0.47753171, -0.23606433, -1.40606645])

In [9]:
np.maximum(x,y)

array([ 0.89424365, -0.20190307,  0.48444   ,  0.89853631,  0.14830707,
        0.28291022, -0.23606433,  0.72912856])

In [15]:
arr2=np.random.randn(7)*5

In [16]:
arr2

array([-10.0753972 ,   6.46374032,  -6.23411251,   3.02866883,
         3.60611812,  -8.77444762, -10.00764875])

In [17]:
remainder, whole_part=np.modf(arr2)

In [18]:
remainder

array([-0.0753972 ,  0.46374032, -0.23411251,  0.02866883,  0.60611812,
       -0.77444762, -0.00764875])

In [19]:
whole_part

array([-10.,   6.,  -6.,   3.,   3.,  -8., -10.])

In [20]:
np.sqrt(arr2)

C:\Users\stepheny.sisi.yuan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 2.5423887 ,        nan, 1.74030711, 1.89897818,
              nan,        nan])

In [21]:
arr2

array([-10.0753972 ,   6.46374032,  -6.23411251,   3.02866883,
         3.60611812,  -8.77444762, -10.00764875])

In [22]:
np.sqrt(arr2, arr2)

C:\Users\stepheny.sisi.yuan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 2.5423887 ,        nan, 1.74030711, 1.89897818,
              nan,        nan])

In [23]:
arr2

array([       nan, 2.5423887 ,        nan, 1.74030711, 1.89897818,
              nan,        nan])

In [28]:
arr3 = np.random.randn(10)

In [29]:
arr3

array([ 0.26789167,  0.52110301,  1.17951094, -1.41455009, -0.74838369,
        0.96899006, -1.05793634, -0.41846582, -0.08087821, -0.54311931])

In [31]:
np.fabs(arr3)

array([0.26789167, 0.52110301, 1.17951094, 1.41455009, 0.74838369,
       0.96899006, 1.05793634, 0.41846582, 0.08087821, 0.54311931])

In [32]:
np.abs(arr3)

array([0.26789167, 0.52110301, 1.17951094, 1.41455009, 0.74838369,
       0.96899006, 1.05793634, 0.41846582, 0.08087821, 0.54311931])

In [33]:
np.square(arr3)

array([0.07176595, 0.27154835, 1.39124606, 2.00095197, 0.56007814,
       0.93894174, 1.1192293 , 0.17511365, 0.00654128, 0.29497858])

In [35]:
np.log2(arr3)

C:\Users\stepheny.sisi.yuan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log2
  """Entry point for launching an IPython kernel.


array([-1.90027836, -0.9403595 ,  0.2381888 ,         nan,         nan,
       -0.04544622,         nan,         nan,         nan,         nan])

In [36]:
np.logical_not(arr3)

array([False, False, False, False, False, False, False, False, False,
       False])

In [37]:
arr3[5] = 0

In [38]:
arr3

array([ 0.26789167,  0.52110301,  1.17951094, -1.41455009, -0.74838369,
        0.        , -1.05793634, -0.41846582, -0.08087821, -0.54311931])

In [39]:
~arr3

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [42]:
arr4=np.array([True, False, True, True, False])

In [43]:
~arr4

array([False,  True, False, False,  True])

In [44]:
arr5 = np.array([False,False,True,True,False])

In [46]:
np.logical_and(arr4,arr5)

array([False, False,  True,  True, False])

In [47]:
np.logical_or(arr4,arr5)

array([ True, False,  True,  True, False])

In [48]:
np.logical_xor(arr4,arr5)

array([ True, False, False, False, False])