In [1]:
import numpy as np

In [2]:
arr=np.arange(10000)

In [3]:
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [4]:
np.save('array_numbers', arr)

In [5]:
np.load('array_numbers.npy')

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [6]:
np.savez('array_archive.npz',a=arr,b=arr)

In [7]:
arch=np.load('array_archive.npz')

In [8]:
arch['b']

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [9]:
np.savez_compressed('array_compressed.npz',a=arr,b=arr)