In [4]:
import numpy as np

In [5]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [6]:
data = np.random.randn(7,4)

In [7]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [8]:
data

array([[-0.75090491,  1.47467318,  0.48670676,  0.03538495],
       [-1.40150993, -1.20623809,  0.05463139, -0.59501663],
       [ 1.43783755,  1.83262368,  1.49073322, -0.95643113],
       [-0.06261741, -0.29447969,  0.75518318, -1.27957284],
       [-1.07608053,  1.18292227,  0.5484099 ,  1.00470225],
       [ 1.33918691, -2.80399554,  1.93581801, -0.90728088],
       [-0.2313289 ,  2.06695776, -0.74167255,  1.45489247]])

In [9]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [10]:
data[names=='Bob']

array([[-0.75090491,  1.47467318,  0.48670676,  0.03538495],
       [-0.06261741, -0.29447969,  0.75518318, -1.27957284]])

In [11]:
data[names!='Bob']

array([[-1.40150993, -1.20623809,  0.05463139, -0.59501663],
       [ 1.43783755,  1.83262368,  1.49073322, -0.95643113],
       [-1.07608053,  1.18292227,  0.5484099 ,  1.00470225],
       [ 1.33918691, -2.80399554,  1.93581801, -0.90728088],
       [-0.2313289 ,  2.06695776, -0.74167255,  1.45489247]])

In [12]:
data[~(names=='Bob')]

array([[-1.40150993, -1.20623809,  0.05463139, -0.59501663],
       [ 1.43783755,  1.83262368,  1.49073322, -0.95643113],
       [-1.07608053,  1.18292227,  0.5484099 ,  1.00470225],
       [ 1.33918691, -2.80399554,  1.93581801, -0.90728088],
       [-0.2313289 ,  2.06695776, -0.74167255,  1.45489247]])

In [13]:
cond = names=='Bob'

In [14]:
data[~cond]

array([[-1.40150993, -1.20623809,  0.05463139, -0.59501663],
       [ 1.43783755,  1.83262368,  1.49073322, -0.95643113],
       [-1.07608053,  1.18292227,  0.5484099 ,  1.00470225],
       [ 1.33918691, -2.80399554,  1.93581801, -0.90728088],
       [-0.2313289 ,  2.06695776, -0.74167255,  1.45489247]])

In [69]:
mask1 = (names=='Bob')|(names=='Will')

In [75]:
mask1

array([ True, False,  True,  True,  True, False, False])

In [80]:
data[mask1]

array([[-0.75090491,  1.47467318,  0.48670676,  0.03538495],
       [ 1.43783755,  1.83262368,  1.49073322, -0.95643113],
       [-0.06261741, -0.29447969,  0.75518318, -1.27957284],
       [-1.07608053,  1.18292227,  0.5484099 ,  1.00470225]])