In [5]:
import pandas as pd
import numpy as np

In [4]:
data=pd.DataFrame(np.random.randn(1000,4))

In [5]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.009358     0.002151    -0.034422     0.004989
std       1.001987     0.975506     0.994069     1.014078
min      -3.393743    -3.242394    -3.078412    -3.383517
25%      -0.653390    -0.648862    -0.714466    -0.682407
50%       0.031018     0.066418    -0.057089    -0.003065
75%       0.665461     0.660051     0.671731     0.677222
max       3.193271     3.292391     3.622262     3.710030

In [6]:
col=data[1]

In [7]:
col[np.abs(col)>3]

61    -3.242394
95    -3.120564
598    3.292391
Name: 1, dtype: float64

In [8]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
61   0.057320 -3.242394  0.221478 -1.598117
95  -0.544628 -3.120564  1.622798  0.725066
150 -3.092469  0.828885  0.185594 -0.497214
267 -1.352623 -0.266987  3.622262 -0.573329
303  3.193271 -0.833741  1.598603  0.189731
365 -0.909131  0.500709 -3.078412 -0.386733
368 -3.393743 -0.008511 -1.298897  1.337601
598  0.753587  3.292391 -1.088363 -0.328940
719 -0.548964 -0.731262 -0.836459  3.576283
840 -3.127858  0.365996 -0.648815 -0.322927
913 -0.189947 -0.742226  1.243851 -3.203753
989 -0.653439 -0.647532 -0.612294 -3.383517
996  1.208153 -1.655483 -1.067487  3.710030

In [11]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
61   0.057320 -3.242394  0.221478 -1.598117
95  -0.544628 -3.120564  1.622798  0.725066
150 -3.092469  0.828885  0.185594 -0.497214
267 -1.352623 -0.266987  3.622262 -0.573329
303  3.193271 -0.833741  1.598603  0.189731
365 -0.909131  0.500709 -3.078412 -0.386733
368 -3.393743 -0.008511 -1.298897  1.337601
598  0.753587  3.292391 -1.088363 -0.328940
719 -0.548964 -0.731262 -0.836459  3.576283
840 -3.127858  0.365996 -0.648815 -0.322927
913 -0.189947 -0.742226  1.243851 -3.203753
989 -0.653439 -0.647532 -0.612294 -3.383517
996  1.208153 -1.655483 -1.067487  3.710030

In [13]:
data[np.abs(data)>3]=np.sign(data)*3

In [14]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.009778     0.002222    -0.034966     0.004290
std       0.999451     0.973405     0.991733     1.008009
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.653390    -0.648862    -0.714466    -0.682407
50%       0.031018     0.066418    -0.057089    -0.003065
75%       0.665461     0.660051     0.671731     0.677222
max       3.000000     3.000000     3.000000     3.000000

In [15]:
np.sign(data).head(10)

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1  1.0 -1.0 -1.0 -1.0
2  1.0  1.0  1.0  1.0
3 -1.0 -1.0 -1.0  1.0
4  1.0  1.0 -1.0  1.0
5  1.0  1.0 -1.0 -1.0
6  1.0  1.0 -1.0  1.0
7  1.0  1.0 -1.0 -1.0
8 -1.0 -1.0  1.0  1.0
9 -1.0 -1.0  1.0 -1.0

In [37]:
df=pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [38]:
sampler=np.random.permutation(5)

In [39]:
sampler

array([3, 4, 0, 1, 2])

In [40]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [41]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11

In [42]:
df.sample(n=3)

0  1   2   3
2  8  9  10  11
0  0  1   2   3
1  4  5   6   7

In [43]:
choices=pd.Series([5,7,-1,6,4])

In [44]:
draws=choices.sample(n=10, replace=True)

In [45]:
draws

3    6
1    7
2   -1
3    6
0    5
3    6
3    6
3    6
0    5
4    4
dtype: int64

In [46]:
df2=pd.DataFrame({'key':['b','b','a','c','a','b'],
                'data1':range(6)})

In [48]:
pd.get_dummies(df2['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [49]:
dummies=pd.get_dummies(df2['key'], prefix='key')

In [50]:
df_with_dummy=df2[['data1']].join(dummies)

In [51]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [6]:
mnames=['movie_id','title','genres']

In [12]:
movies=pd.read_table('movies.dat', sep='::',
                    header=None, names=mnames)

C:\Users\stepheny.sisi.yuan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [13]:
movies[:100]

movie_id                                 title  \
0          1                      Toy Story (1995)   
1          2                        Jumanji (1995)   
2          3               Grumpier Old Men (1995)   
3          4              Waiting to Exhale (1995)   
4          5    Father of the Bride Part II (1995)   
..       ...                                   ...   
95        97               Hate (Haine, La) (1995)   
96        98                       Shopping (1994)   
97        99  Heidi Fleiss: Hollywood Madam (1995)   
98       100                      City Hall (1996)   
99       101                  Bottle Rocket (1996)   

                          genres  
0    Animation|Children's|Comedy  
1   Adventure|Children's|Fantasy  
2                 Comedy|Romance  
3                   Comedy|Drama  
4                         Comedy  
..                           ...  
95                         Drama  
96               Action|Thriller  
97                   Documentary  
98                Drama|Thriller  
99                        Comedy  

[100 rows x 3 columns]

In [14]:
all_genres=[]

In [15]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [16]:
genres=pd.unique(all_genres)

In [17]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [21]:
zero_matrix=np.zeros((len(movies), len(genres)))

In [22]:
dummies=pd.DataFrame(zero_matrix, columns=genres)

In [23]:
gen=movies.genres[0]

In [24]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [25]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [26]:
for i, gen in enumerate(movies.genres):
    indices=dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices]=1

In [27]:
movies_windic=movies.join(dummies.add_prefix('Gene_'))

In [30]:
movies_windic.iloc[1]

movie_id                                       2
title                             Jumanji (1995)
genres              Adventure|Children's|Fantasy
Gene_Animation                                 0
Gene_Children's                                1
Gene_Comedy                                    0
Gene_Adventure                                 1
Gene_Fantasy                                   1
Gene_Romance                                   0
Gene_Drama                                     0
Gene_Action                                    0
Gene_Crime                                     0
Gene_Thriller                                  0
Gene_Horror                                    0
Gene_Sci-Fi                                    0
Gene_Documentary                               0
Gene_War                                       0
Gene_Musical                                   0
Gene_Mystery                                   0
Gene_Film-Noir                                 0
Gene_Western        

In [31]:
np.random.seed(12345)

In [32]:
values=np.random.rand(10)

In [33]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [34]:
bins=[0,0.2,0.4,0.6,0.8,1]

In [35]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0