In [3]:
from numpy.linalg import inv,qr
import numpy as np

In [8]:
X=np.random.randn(5,5)

In [15]:
mat=X.T.dot(X)

In [16]:
mat

array([[ 6.46327543,  0.94069011, -1.99807036, -3.58276931, -5.09483371],
       [ 0.94069011,  1.21409404, -1.15047152,  0.14891893,  0.28205119],
       [-1.99807036, -1.15047152,  2.43699211,  0.41894591,  1.58346314],
       [-3.58276931,  0.14891893,  0.41894591,  3.22799927,  2.65129774],
       [-5.09483371,  0.28205119,  1.58346314,  2.65129774,  7.08570851]])

In [10]:
inv(mat)

array([[ 2.87258422, -3.47052579, -0.65566631,  2.17017189,  1.53811809],
       [-3.47052579,  6.21535386,  1.97466073, -2.56935965, -2.22270854],
       [-0.65566631,  1.97466073,  1.32424518, -0.42711653, -0.68616237],
       [ 2.17017189, -2.56935965, -0.42711653,  2.0910287 ,  0.97573016],
       [ 1.53811809, -2.22270854, -0.68616237,  0.97573016,  1.12380225]])

In [11]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.77635684e-15,  0.00000000e+00,
         0.00000000e+00, -8.88178420e-16],
       [ 5.55111512e-16,  1.00000000e+00, -3.05311332e-16,
         2.22044605e-16, -1.11022302e-16],
       [ 0.00000000e+00,  8.88178420e-16,  1.00000000e+00,
         0.00000000e+00,  2.22044605e-16],
       [ 8.88178420e-16,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  1.33226763e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.88178420e-16,  1.00000000e+00]])

In [12]:
q,r=qr(mat)

In [13]:
r

array([[-9.24362909, -0.81680068,  3.07607171,  5.292999  ,  8.80902462],
       [ 0.        , -1.76552352,  1.73234258, -1.06505385, -1.87855097],
       [ 0.        ,  0.        , -1.21426673,  0.72286499, -1.8134752 ],
       [ 0.        ,  0.        ,  0.        , -0.90031969,  1.12438567],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.3163537 ]])

In [14]:
q

array([[-0.69921406, -0.20932691, -0.42444394, -0.22441055,  0.48658935],
       [-0.10176632, -0.6405869 , -0.22423816, -0.18593654, -0.70316206],
       [ 0.21615648,  0.55162944, -0.672396  , -0.38696971, -0.21707   ],
       [ 0.38759337, -0.26366426,  0.2607024 , -0.78549731,  0.30867584],
       [ 0.55117245, -0.41474906, -0.49948219,  0.38511807,  0.355519  ]])

In [28]:
ints=np.random.randint(5)

In [29]:
ints

4

In [30]:
samples=np.random.normal(size=(4,4))

In [31]:
samples

array([[-0.46881538, -0.22809707,  0.03438385, -0.66557897],
       [ 0.19243484, -1.19208645,  1.33037573, -0.90807917],
       [ 0.93961014, -0.48341345,  0.38596352, -0.02392707],
       [-0.38463402, -0.30604497, -0.11588386,  0.35373932]])

In [32]:
from random import normalvariate

In [33]:
N=1000000

In [35]:
%timeit samples=[normalvariate(0,1) for _ in range(N)]

4.39 s ± 427 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [36]:
%timeit np.random.normal(size=N)

140 ms ± 9.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [38]:
rng=np.random.RandomState(1223)

In [39]:
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [45]:
mat = np.array([1,2,3])

In [48]:
np.random.shuffle(mat)

In [49]:
mat

array([1, 3, 2])

In [53]:
mat2 = np.matrix([4,5,6])

In [54]:
np.random.shuffle(mat2)

In [55]:
mat2

matrix([[4, 5, 6]])