In [1]:
import numpy as np

In [2]:
np.ones(3)

array([1., 1., 1.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
x=np.array([[1,2,3],[4,5,6]])

In [7]:
y=np.array([[6,23],[-1,7],[8,9]])

In [8]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [10]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [11]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [12]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [13]:
x@np.ones(3)

array([ 6., 15.])

In [14]:
x.dot(np.ones(3))

array([ 6., 15.])